- id: '1705251620297'
  name: Pogoda
  entities:
    weather.openweathermap:
      temperature: 1.6
      apparent_temperature: -3.9
      temperature_unit: °C
      humidity: 94
      cloud_coverage: 75
      pressure: 997
      pressure_unit: hPa
      wind_bearing: 250
      wind_speed: 25.92
      wind_speed_unit: km/h
      visibility_unit: km
      precipitation_unit: mm
      forecast:
      - condition: snowy
        precipitation_probability: 29
        datetime: '2024-01-14T18:00:00+00:00'
        wind_bearing: 248
        cloud_coverage: 75
        temperature: 1.6
        pressure: 997
        wind_speed: 25.49
        precipitation: 0.45
        humidity: 94
      - condition: snowy
        precipitation_probability: 29
        datetime: '2024-01-14T21:00:00+00:00'
        wind_bearing: 240
        cloud_coverage: 83
        temperature: 1.2
        pressure: 997
        wind_speed: 24.88
        precipitation: 0.3
        humidity: 95
      - condition: snowy
        precipitation_probability: 45
        datetime: '2024-01-15T00:00:00+00:00'
        wind_bearing: 245
        cloud_coverage: 92
        temperature: 0.9
        pressure: 995
        wind_speed: 28.01
        precipitation: 0.15
        humidity: 92
      - condition: snowy
        precipitation_probability: 80
        datetime: '2024-01-15T03:00:00+00:00'
        wind_bearing: 237
        cloud_coverage: 100
        temperature: 0.2
        pressure: 991
        wind_speed: 30.56
        precipitation: 0.49
        humidity: 93
      - condition: snowy
        precipitation_probability: 86
        datetime: '2024-01-15T06:00:00+00:00'
        wind_bearing: 247
        cloud_coverage: 100
        temperature: 0.4
        pressure: 989
        wind_speed: 32.15
        precipitation: 0.58
        humidity: 87
      - condition: snowy
        precipitation_probability: 65
        datetime: '2024-01-15T09:00:00+00:00'
        wind_bearing: 251
        cloud_coverage: 92
        temperature: 0.1
        pressure: 989
        wind_speed: 36.58
        precipitation: 0.35
        humidity: 89
      - condition: snowy
        precipitation_probability: 74
        datetime: '2024-01-15T12:00:00+00:00'
        wind_bearing: 259
        cloud_coverage: 96
        temperature: 0.9
        pressure: 990
        wind_speed: 33.52
        precipitation: 0.36
        humidity: 80
      - condition: snowy
        precipitation_probability: 51
        datetime: '2024-01-15T15:00:00+00:00'
        wind_bearing: 254
        cloud_coverage: 97
        temperature: 0.2
        pressure: 990
        wind_speed: 31.86
        precipitation: 0.36
        humidity: 90
      - condition: snowy
        precipitation_probability: 97
        datetime: '2024-01-15T18:00:00+00:00'
        wind_bearing: 283
        cloud_coverage: 92
        temperature: -1.5
        pressure: 992
        wind_speed: 32.15
        precipitation: 0.6
        humidity: 77
      - condition: cloudy
        precipitation_probability: 6
        datetime: '2024-01-15T21:00:00+00:00'
        wind_bearing: 282
        cloud_coverage: 92
        temperature: -2.4
        pressure: 995
        wind_speed: 30.85
        precipitation: 0
        humidity: 88
      - condition: snowy
        precipitation_probability: 25
        datetime: '2024-01-16T00:00:00+00:00'
        wind_bearing: 294
        cloud_coverage: 96
        temperature: -2.8
        pressure: 999
        wind_speed: 27
        precipitation: 0.14
        humidity: 85
      - condition: cloudy
        precipitation_probability: 0
        datetime: '2024-01-16T03:00:00+00:00'
        wind_bearing: 287
        cloud_coverage: 100
        temperature: -3.7
        pressure: 1003
        wind_speed: 20.48
        precipitation: 0
        humidity: 86
      - condition: cloudy
        precipitation_probability: 0
        datetime: '2024-01-16T06:00:00+00:00'
        wind_bearing: 291
        cloud_coverage: 100
        temperature: -3.7
        pressure: 1005
        wind_speed: 16.63
        precipitation: 0
        humidity: 88
      - condition: cloudy
        precipitation_probability: 4
        datetime: '2024-01-16T09:00:00+00:00'
        wind_bearing: 281
        cloud_coverage: 97
        temperature: -3
        pressure: 1008
        wind_speed: 13.18
        precipitation: 0
        humidity: 85
      - condition: cloudy
        precipitation_probability: 4
        datetime: '2024-01-16T12:00:00+00:00'
        wind_bearing: 254
        cloud_coverage: 77
        temperature: -2
        pressure: 1009
        wind_speed: 12.31
        precipitation: 0
        humidity: 77
      - condition: partlycloudy
        precipitation_probability: 0
        datetime: '2024-01-16T15:00:00+00:00'
        wind_bearing: 225
        cloud_coverage: 48
        temperature: -2.8
        pressure: 1010
        wind_speed: 13.57
        precipitation: 0
        humidity: 87
      - condition: cloudy
        precipitation_probability: 0
        datetime: '2024-01-16T18:00:00+00:00'
        wind_bearing: 232
        cloud_coverage: 74
        temperature: -2.1
        pressure: 1009
        wind_speed: 19.91
        precipitation: 0
        humidity: 90
      - condition: cloudy
        precipitation_probability: 3
        datetime: '2024-01-16T21:00:00+00:00'
        wind_bearing: 233
        cloud_coverage: 100
        temperature: -1.6
        pressure: 1009
        wind_speed: 24.05
        precipitation: 0
        humidity: 86
      - condition: cloudy
        precipitation_probability: 0
        datetime: '2024-01-17T00:00:00+00:00'
        wind_bearing: 235
        cloud_coverage: 92
        temperature: -2.5
        pressure: 1009
        wind_speed: 20.99
        precipitation: 0
        humidity: 89
      - condition: partlycloudy
        precipitation_probability: 0
        datetime: '2024-01-17T03:00:00+00:00'
        wind_bearing: 218
        cloud_coverage: 44
        temperature: -3.4
        pressure: 1009
        wind_speed: 17.24
        precipitation: 0
        humidity: 91
      - condition: cloudy
        precipitation_probability: 0
        datetime: '2024-01-17T06:00:00+00:00'
        wind_bearing: 197
        cloud_coverage: 57
        temperature: -3.3
        pressure: 1007
        wind_speed: 18.65
        precipitation: 0
        humidity: 86
      - condition: cloudy
        precipitation_probability: 0
        datetime: '2024-01-17T09:00:00+00:00'
        wind_bearing: 192
        cloud_coverage: 100
        temperature: -1.9
        pressure: 1004
        wind_speed: 21.46
        precipitation: 0
        humidity: 80
      - condition: cloudy
        precipitation_probability: 0
        datetime: '2024-01-17T12:00:00+00:00'
        wind_bearing: 197
        cloud_coverage: 100
        temperature: -0.5
        pressure: 1001
        wind_speed: 21.17
        precipitation: 0
        humidity: 74
      - condition: cloudy
        precipitation_probability: 0
        datetime: '2024-01-17T15:00:00+00:00'
        wind_bearing: 193
        cloud_coverage: 100
        temperature: -1.5
        pressure: 999
        wind_speed: 15.16
        precipitation: 0
        humidity: 81
      - condition: cloudy
        precipitation_probability: 0
        datetime: '2024-01-17T18:00:00+00:00'
        wind_bearing: 196
        cloud_coverage: 100
        temperature: -1.5
        pressure: 998
        wind_speed: 12.96
        precipitation: 0
        humidity: 85
      - condition: cloudy
        precipitation_probability: 0
        datetime: '2024-01-17T21:00:00+00:00'
        wind_bearing: 192
        cloud_coverage: 100
        temperature: -1.5
        pressure: 997
        wind_speed: 11.74
        precipitation: 0
        humidity: 91
      - condition: snowy
        precipitation_probability: 29
        datetime: '2024-01-18T00:00:00+00:00'
        wind_bearing: 190
        cloud_coverage: 100
        temperature: -1.6
        pressure: 995
        wind_speed: 7.85
        precipitation: 0.27
        humidity: 98
      - condition: snowy
        precipitation_probability: 71
        datetime: '2024-01-18T03:00:00+00:00'
        wind_bearing: 249
        cloud_coverage: 100
        temperature: -1.6
        pressure: 994
        wind_speed: 1.58
        precipitation: 0.83
        humidity: 99
      - condition: snowy
        precipitation_probability: 74
        datetime: '2024-01-18T06:00:00+00:00'
        wind_bearing: 28
        cloud_coverage: 100
        temperature: -1.9
        pressure: 994
        wind_speed: 4.72
        precipitation: 0.54
        humidity: 99
      - condition: snowy
        precipitation_probability: 98
        datetime: '2024-01-18T09:00:00+00:00'
        wind_bearing: 31
        cloud_coverage: 100
        temperature: -0.9
        pressure: 995
        wind_speed: 8.68
        precipitation: 0.55
        humidity: 97
      - condition: snowy
        precipitation_probability: 67
        datetime: '2024-01-18T12:00:00+00:00'
        wind_bearing: 14
        cloud_coverage: 99
        temperature: -0.5
        pressure: 995
        wind_speed: 8.89
        precipitation: 0.27
        humidity: 94
      - condition: snowy
        precipitation_probability: 59
        datetime: '2024-01-18T15:00:00+00:00'
        wind_bearing: 339
        cloud_coverage: 100
        temperature: -1.1
        pressure: 997
        wind_speed: 9.4
        precipitation: 0.34
        humidity: 97
      - condition: cloudy
        precipitation_probability: 30
        datetime: '2024-01-18T18:00:00+00:00'
        wind_bearing: 304
        cloud_coverage: 100
        temperature: -1.6
        pressure: 999
        wind_speed: 10.73
        precipitation: 0
        humidity: 94
      - condition: cloudy
        precipitation_probability: 0
        datetime: '2024-01-18T21:00:00+00:00'
        wind_bearing: 312
        cloud_coverage: 100
        temperature: -1.6
        pressure: 1003
        wind_speed: 18.47
        precipitation: 0
        humidity: 92
      - condition: cloudy
        precipitation_probability: 0
        datetime: '2024-01-19T00:00:00+00:00'
        wind_bearing: 305
        cloud_coverage: 72
        temperature: -4
        pressure: 1007
        wind_speed: 17.17
        precipitation: 0
        humidity: 88
      - condition: clear-night
        precipitation_probability: 0
        datetime: '2024-01-19T03:00:00+00:00'
        wind_bearing: 294
        cloud_coverage: 8
        temperature: -4.9
        pressure: 1010
        wind_speed: 16.45
        precipitation: 0
        humidity: 90
      - condition: partlycloudy
        precipitation_probability: 0
        datetime: '2024-01-19T06:00:00+00:00'
        wind_bearing: 283
        cloud_coverage: 19
        temperature: -5.7
        pressure: 1014
        wind_speed: 13.03
        precipitation: 0
        humidity: 94
      - condition: sunny
        precipitation_probability: 0
        datetime: '2024-01-19T09:00:00+00:00'
        wind_bearing: 270
        cloud_coverage: 8
        temperature: -4.8
        pressure: 1017
        wind_speed: 11.59
        precipitation: 0
        humidity: 92
      - condition: sunny
        precipitation_probability: 0
        datetime: '2024-01-19T12:00:00+00:00'
        wind_bearing: 258
        cloud_coverage: 8
        temperature: -3.2
        pressure: 1018
        wind_speed: 13.54
        precipitation: 0
        humidity: 87
      - condition: sunny
        precipitation_probability: 0
        datetime: '2024-01-19T15:00:00+00:00'
        wind_bearing: 239
        cloud_coverage: 9
        temperature: -4.7
        pressure: 1020
        wind_speed: 10.62
        precipitation: 0
        humidity: 91
      attribution: Data provided by OpenWeatherMap
      friendly_name: OpenWeatherMap
      supported_features: 2
      state: snowy
    sensor.openweathermap_cloud_coverage:
      state_class: measurement
      unit_of_measurement: '%'
      attribution: Data provided by OpenWeatherMap
      friendly_name: OpenWeatherMap Cloud coverage
      state: '75'
    sensor.openweathermap_condition:
      attribution: Data provided by OpenWeatherMap
      friendly_name: OpenWeatherMap Condition
      state: snowy
    sensor.openweathermap_dew_point:
      state_class: measurement
      unit_of_measurement: °C
      attribution: Data provided by OpenWeatherMap
      device_class: temperature
      friendly_name: OpenWeatherMap Dew Point
      state: unknown
    sensor.openweathermap_feels_like_temperature:
      state_class: measurement
      unit_of_measurement: °C
      attribution: Data provided by OpenWeatherMap
      device_class: temperature
      friendly_name: OpenWeatherMap Feels like temperature
      state: '-3.94'
    sensor.openweathermap_forecast_cloud_coverage:
      unit_of_measurement: '%'
      attribution: Data provided by OpenWeatherMap
      friendly_name: OpenWeatherMap Forecast Cloud coverage
      state: '75'
    sensor.openweathermap_forecast_condition:
      attribution: Data provided by OpenWeatherMap
      friendly_name: OpenWeatherMap Forecast Condition
      state: snowy
    sensor.openweathermap_forecast_precipitation:
      unit_of_measurement: mm
      attribution: Data provided by OpenWeatherMap
      device_class: precipitation
      friendly_name: OpenWeatherMap Forecast Precipitation
      state: '0.45'
    sensor.openweathermap_forecast_precipitation_probability:
      unit_of_measurement: '%'
      attribution: Data provided by OpenWeatherMap
      friendly_name: OpenWeatherMap Forecast Precipitation probability
      state: '29'
    sensor.openweathermap_forecast_pressure:
      unit_of_measurement: hPa
      attribution: Data provided by OpenWeatherMap
      device_class: pressure
      friendly_name: OpenWeatherMap Forecast Pressure
      state: '997'
    sensor.openweathermap_forecast_temperature:
      unit_of_measurement: °C
      attribution: Data provided by OpenWeatherMap
      device_class: temperature
      friendly_name: OpenWeatherMap Forecast Temperature
      state: '1.6'
    sensor.openweathermap_forecast_temperature_low:
      unit_of_measurement: °C
      attribution: Data provided by OpenWeatherMap
      device_class: temperature
      friendly_name: OpenWeatherMap Forecast Temperature Low
      state: unknown
    sensor.openweathermap_forecast_time:
      attribution: Data provided by OpenWeatherMap
      device_class: timestamp
      friendly_name: OpenWeatherMap Forecast Time
      state: '2024-01-14T18:00:00+00:00'
    sensor.openweathermap_forecast_wind_bearing:
      unit_of_measurement: °
      attribution: Data provided by OpenWeatherMap
      friendly_name: OpenWeatherMap Forecast Wind bearing
      state: '248'
    sensor.openweathermap_forecast_wind_speed:
      unit_of_measurement: km/h
      attribution: Data provided by OpenWeatherMap
      device_class: wind_speed
      friendly_name: OpenWeatherMap Forecast Wind speed
      state: '25.49'
    sensor.openweathermap_humidity:
      state_class: measurement
      unit_of_measurement: '%'
      attribution: Data provided by OpenWeatherMap
      device_class: humidity
      friendly_name: OpenWeatherMap Humidity
      state: '94'
    sensor.openweathermap_precipitation_kind:
      attribution: Data provided by OpenWeatherMap
      friendly_name: OpenWeatherMap Precipitation kind
      state: Snow
    sensor.openweathermap_pressure:
      state_class: measurement
      unit_of_measurement: hPa
      attribution: Data provided by OpenWeatherMap
      device_class: pressure
      friendly_name: OpenWeatherMap Pressure
      state: '997'
    sensor.openweathermap_rain:
      state_class: measurement
      unit_of_measurement: mm/h
      attribution: Data provided by OpenWeatherMap
      device_class: precipitation_intensity
      friendly_name: OpenWeatherMap Rain
      state: '0'
    sensor.openweathermap_snow:
      state_class: measurement
      unit_of_measurement: mm/h
      attribution: Data provided by OpenWeatherMap
      device_class: precipitation_intensity
      friendly_name: OpenWeatherMap Snow
      state: '0.2'
    sensor.openweathermap_temperature:
      state_class: measurement
      unit_of_measurement: °C
      attribution: Data provided by OpenWeatherMap
      device_class: temperature
      friendly_name: OpenWeatherMap Temperature
      state: '1.6'
    sensor.openweathermap_uv_index:
      state_class: measurement
      unit_of_measurement: UV index
      attribution: Data provided by OpenWeatherMap
      friendly_name: OpenWeatherMap UV Index
      state: unknown
    sensor.openweathermap_visibility:
      state_class: measurement
      unit_of_measurement: m
      attribution: Data provided by OpenWeatherMap
      device_class: distance
      friendly_name: OpenWeatherMap Visibility
      state: '10000'
    sensor.openweathermap_weather:
      attribution: Data provided by OpenWeatherMap
      friendly_name: OpenWeatherMap Weather
      state: słabe opady śniegu
    sensor.openweathermap_weather_code:
      attribution: Data provided by OpenWeatherMap
      friendly_name: OpenWeatherMap Weather Code
      state: '600'
    sensor.openweathermap_wind_bearing:
      state_class: measurement
      unit_of_measurement: °
      attribution: Data provided by OpenWeatherMap
      friendly_name: OpenWeatherMap Wind bearing
      state: '250'
    sensor.openweathermap_wind_speed:
      state_class: measurement
      unit_of_measurement: km/h
      attribution: Data provided by OpenWeatherMap
      device_class: wind_speed
      friendly_name: OpenWeatherMap Wind speed
      state: '25.9'
  icon: mdi:weather-sunny-alert
  metadata: {}
